version: '3.4'

networks:
  studia_network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: studia_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: StudiaDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - studia_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: WebAPI/Dockerfile
    environment:
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=StudiaDB;Username=postgres;Password=root
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - studia_network

volumes:
  db_data:
